using Microsoft.UI.Xaml;

namespace AutoClicker.WinUI;

/// <summary>
/// WinUI 3 application object. <c>Main</c> is generated by the XAML markup compiler targets
/// (see <c>DISABLE_XAML_GENERATED_MAIN</c> for the opt-out); it installs the ComWrappers
/// support shim, calls <see cref="Microsoft.UI.Xaml.Application.Start"/>, and dispatches
/// <see cref="OnLaunched"/> on the UI thread.
/// </summary>
public partial class App : Application
{
    private Window? _window;

    public App()
    {
        InitializeComponent();
    }

    /// <inheritdoc/>
    protected override void OnLaunched(LaunchActivatedEventArgs args)
    {
        _window = new MainWindow();
        _window.Activate();
    }
}
